Add support for foreign members to FeatureWriter.
georust/geojson pull request #232
Opened 2023-09-18 14:04 UTC by dabreegster

- [X] I agree to follow the project's [code of conduct](https://github.com/georust/geo/blob/master/CODE_OF_CONDUCT.md).
- [X] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.

2023-09-20 12:13 UTC, dabreegster commented
Successfully using this in https://github.com/dabreegster/routing-engines/blob/c58cc43832714c3c2ca17105f184b2885313eddd/aggregate_routes/src/osm2network.rs#L350

2023-09-20 12:23 UTC, michaelkirk commented
Hrmm... my inline comment got lost in the ether.

What would you think about changing the API slightly to avoid building up the intermediate JsonObject just to pass it in?

```
pub fn write_foreign_member(&mut self, key: &str, foreign_member: &JsonValue) -> Result<()>;
```

2023-09-20 12:25 UTC, michaelkirk commented on src/feature_writer.rs
>      Started,
```suggestion
    WritingFeatures,
```

2023-09-20 12:25 UTC, michaelkirk commented on src/feature_writer.rs
> +    StartedWithForeignMembers,
```suggestion
    WritingForeignMembers,
```

Maybe clearer?

2023-09-21 07:57 UTC, dabreegster commented on src/feature_writer.rs
>      Started,
Fixed. Thanks, much more clear

2023-09-21 07:59 UTC, dabreegster commented
> What would you think about changing the API slightly to avoid building up the intermediate JsonObject just to pass it in?

Good idea, done. It was an odd API before to only allow one of the calls. Writing one key at a time is much nicer.

2023-09-27 17:14 UTC, michaelkirk requested changes
This gets a little nicer to use if we allow the same value types as `serde_json::to_writer`.

2023-09-27 17:14 UTC, michaelkirk commented on src/feature_writer.rs
> +    pub fn write_foreign_member(&mut self, key: &str, value: &JsonValue) -> Result<()> {
```suggestion
    pub fn write_foreign_member<T: ?Sized + Serialize>(&mut self, key: &str, value: &T) -> Result<()> {
```

2023-09-27 17:14 UTC, michaelkirk commented on src/feature_writer.rs
> +                .write_foreign_member("extra", &json!("string"))
```suggestion
                .write_foreign_member("extra", "string")
```

2023-09-27 17:14 UTC, michaelkirk commented on src/feature_writer.rs
> +                .write_foreign_member("list", &json!([1, 2, 3]))
```suggestion
                .write_foreign_member("list", &[1, 2, 3])
```

2023-09-28 09:35 UTC, dabreegster commented
> This gets a little nicer to use if we allow the same value types as serde_json::to_writer.

Good point, thanks! Done

2023-09-28 22:46 UTC, michaelkirk approved these changes
Thank you!

2023-09-28 22:46 UTC, merged